import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "node:fs";
import path from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Пути для сборки
const BUILD_DIR = "./build";
const TEST_VAULT_PLUGIN_DIR =
	"/Users/swnet/Desktop/obsidian-work/.obsidian/plugins/obsidian-yandex-disk-sync";

// Файлы для копирования
const FILES_TO_COPY = ["manifest.json", "styles.css"];

/**
 * Копирование файлов после сборки
 */
function copyFiles(sourceDir, destDir) {
	// Создаём директории если не существуют
	if (!fs.existsSync(BUILD_DIR)) {
		fs.mkdirSync(BUILD_DIR, { recursive: true });
	}
	if (!fs.existsSync(destDir)) {
		fs.mkdirSync(destDir, { recursive: true });
	}

	// Копируем main.js
	const mainJsSource = path.join(BUILD_DIR, "main.js");
	if (fs.existsSync(mainJsSource)) {
		fs.copyFileSync(mainJsSource, path.join(destDir, "main.js"));
		console.log(`Copied main.js to ${destDir}`);
	}

	// Копируем остальные файлы
	for (const file of FILES_TO_COPY) {
		const sourcePath = path.join(".", file);
		if (fs.existsSync(sourcePath)) {
			// Копируем в build директорию
			fs.copyFileSync(sourcePath, path.join(BUILD_DIR, file));
			// Копируем в тестовый vault
			fs.copyFileSync(sourcePath, path.join(destDir, file));
			console.log(`Copied ${file} to ${BUILD_DIR} and ${destDir}`);
		}
	}
}

/**
 * Плагин для копирования файлов после сборки
 */
const copyPlugin = {
	name: "copy-plugin",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length === 0) {
				copyFiles(BUILD_DIR, TEST_VAULT_PLUGIN_DIR);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: path.join(BUILD_DIR, "main.js"),
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
